### ISSUE TITLE
Bruh momentum is getting out of ✋

### ISSUE THREAD

**Issue by OPuusalu** [MadisJu/MadislolincWeb#9]
Bruh momentum
https://user-images.githubusercontent.com/61630177/148922888-03b6f820-c4f6-4dac-9aec-9f24e356febf.mp4
![unknown-43.jpg](https://user-images.githubusercontent.com/61630177/148923071-8441a156-f76f-4ee3-acea-ffc383fd0401.jpg)

_Originally posted by @MadisJu in https://github.com/MadisJu/MadislolincWeb/issues/8#issuecomment-1009792451_

**Comment by MadisJu** [comment]
Fixed

**Comment by MadisJu** [comment]
Bruh momentum fixed
![IMG_20220111_141205.jpg](https://user-images.githubusercontent.com/61630177/148959628-a891d541-3e8a-4e47-99f3-1e366d5468e1.jpg)

**Comment by MadisJu** [comment]
For fucks sake

**Comment by OPuusalu** [comment]
Yes fuck sake, we still have a problem on ✋. You need to take your shit together!

**Comment by MadisJu** [comment]
Fucks sake, stop playing around kid

**Comment by OPuusalu** [comment]
Nty

**Comment by OPuusalu** [comment]
![IMG_20220112_231431.jpg](https://user-images.githubusercontent.com/91115628/149615618-eb97e618-ec17-4736-a62d-f4e0efdf70e1.jpg)
